#!/usr/bin/env bash
# Interactive quickstart: prompt for .env values, choose dry/paper/live mode, then docker compose build + up.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

die() {
  echo "Error: $*" >&2
  exit 1
}

command -v docker >/dev/null 2>&1 || die "docker not found. Install Docker Desktop or the Docker Engine CLI."

if ! docker compose version >/dev/null 2>&1; then
  die "docker compose not available. Use Docker Compose V2 (docker compose)."
fi

rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    printf '%x' "$RANDOM$RANDOM$RANDOM$RANDOM" | head -c 32
    echo
  fi
}

rand_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr -d '\n'
  else
    rand_hex
    rand_hex
  fi
}

read_default() {
  local prompt="$1" default="$2"
  local input
  read -r -p "${prompt} [${default}]: " input || true
  if [[ -z "${input:-}" ]]; then
    printf '%s' "$default"
  else
    printf '%s' "$input"
  fi
}

read_optional_empty() {
  local prompt="$1"
  local input
  read -r -p "${prompt} (leave empty to skip): " input || true
  printf '%s' "${input:-}"
}

read_secret_optional() {
  local prompt="$1"
  local input
  read -r -s -p "${prompt} (leave empty to skip): " input || true
  echo ""
  printf '%s' "${input:-}"
}

select_run_mode() {
  echo ""
  echo "Run mode:"
  echo "  1) dry   — dashboard + ingest + alerts only (no trading-worker, agent off)"
  echo "  2) paper — closed loop with simulated order fills (trading-worker + agent trades)"
  echo "  3) live  — real Coinbase order execution (requires trade keys + TRADING_LIVE_ACK)"
  echo ""
  local choice
  read -r -p "Choose mode [1]: " choice || true
  case "${choice:-1}" in
    1|dry|Dry|DRY) RUN_MODE="dry" ;;
    2|paper|Paper|PAPER) RUN_MODE="paper" ;;
    3|live|Live|LIVE) RUN_MODE="live" ;;
    *) RUN_MODE="dry" ;;
  esac
}

confirm_live_mode() {
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " LIVE MODE WARNING"
  echo ""
  echo " Live mode submits real market orders to Coinbase when the agent or MCP creates trades."
  echo " Set TRADING_MAX_NOTIONAL low and keep TRADING_KILL_SWITCH=true until you are ready."
  echo " Requires TRADING_LIVE_ACK=true (set automatically by this script)."
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  local ack
  read -r -p "Type LIVE to continue configuring live mode: " ack || true
  [[ "${ack:-}" == "LIVE" ]] || die "Live mode setup cancelled."
}

write_env_file() {
  local DATABASE_URL
  DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable"

  local TRADING_ENABLED="false"
  local TRADING_KILL_SWITCH="false"
  local TRADING_BROKER_ENV="paper"
  local AGENT_ENABLED="false"
  local AGENT_PROVIDER="mock"
  local AGENT_TRADE_ENABLED="false"
  local TRADING_LIVE_ACK="false"
  local TRADING_LIVE_MAX_NOTIONAL_CAP="500"

  case "$RUN_MODE" in
    paper)
      TRADING_ENABLED="true"
      TRADING_BROKER_ENV="paper"
      AGENT_ENABLED="true"
      AGENT_PROVIDER="anthropic"
      AGENT_TRADE_ENABLED="true"
      ;;
    live)
      TRADING_ENABLED="true"
      TRADING_BROKER_ENV="live"
      AGENT_ENABLED="true"
      AGENT_PROVIDER="anthropic"
      AGENT_TRADE_ENABLED="true"
      TRADING_LIVE_ACK="true"
      ;;
  esac

  : > .env
  {
    printf '%s\n' '# Generated by scripts/quickstart.sh — keep secret; do not commit.'
    printf '%s\n' ''
    printf '%s\n' '# Database'
    printf 'POSTGRES_USER=%s\n' "$POSTGRES_USER"
    printf 'POSTGRES_PASSWORD=%s\n' "$POSTGRES_PASSWORD"
    printf 'POSTGRES_DB=%s\n' "$POSTGRES_DB"
    printf 'DATABASE_URL=%s\n' "$DATABASE_URL"
    printf '%s\n' ''
    printf '%s\n' '# Broker routing'
    printf 'BROKER_PROVIDER=coinbase\n'
    printf 'BROKER_ENV=%s\n' "$TRADING_BROKER_ENV"
    printf 'INGEST_BROKER_PROVIDER=coinbase\n'
    printf 'INGEST_BROKER_ENV=paper\n'
    printf 'PORTFOLIO_BROKER_PROVIDER=coinbase\n'
    printf 'PORTFOLIO_BROKER_ENV=paper\n'
    printf 'TRADING_BROKER_PROVIDER=coinbase\n'
    printf 'TRADING_BROKER_ENV=%s\n' "$TRADING_BROKER_ENV"
    printf '%s\n' ''
    printf '%s\n' '# Coinbase read API (CDP — accounts, quotes, snapshots)'
    printf 'COINBASE_READ_API_KEY=%s\n' "${COINBASE_READ_API_KEY:-}"
    printf 'COINBASE_READ_API_SECRET=%s\n' "${COINBASE_READ_API_SECRET:-}"
    printf '%s\n' ''
    printf '%s\n' '# Coinbase trade API (execution — required for live mode)'
    printf 'COINBASE_TRADE_API_KEY=%s\n' "${COINBASE_TRADE_API_KEY:-}"
    printf 'COINBASE_TRADE_API_SECRET=%s\n' "${COINBASE_TRADE_API_SECRET:-}"
    printf '%s\n' ''
    printf '%s\n' '# Trading policy'
    printf 'TRADING_ENABLED=%s\n' "$TRADING_ENABLED"
    printf 'TRADING_KILL_SWITCH=%s\n' "$TRADING_KILL_SWITCH"
    printf 'TRADING_MAX_NOTIONAL=%s\n' "${TRADING_MAX_NOTIONAL:-1000}"
    printf 'TRADING_RESERVE=%s\n' "${TRADING_RESERVE:-300}"
    printf 'TRADING_MIN_HOLDINGS=%s\n' "${TRADING_MIN_HOLDINGS:-BTC-USD:0.0075,SOL-USD:4}"
    printf 'TRADING_GLOBAL_MAX_EXPOSURE=%s\n' "${TRADING_GLOBAL_MAX_EXPOSURE:-5000}"
    printf 'TRADING_SYMBOL_COOLDOWN=%s\n' "${TRADING_SYMBOL_COOLDOWN:-5m}"
    printf 'TRADING_ALLOWED_PROVIDERS=%s\n' "${TRADING_ALLOWED_PROVIDERS:-coinbase}"
    printf 'TRADING_ALLOWED_SYMBOLS=%s\n' "${TRADING_ALLOWED_SYMBOLS:-BTC-USD,ETH-USD}"
    printf 'TRADING_DENIED_SYMBOLS=%s\n' "${TRADING_DENIED_SYMBOLS:-}"
    printf 'TRADING_LIVE_ACK=%s\n' "$TRADING_LIVE_ACK"
    printf 'TRADING_LIVE_MAX_NOTIONAL_CAP=%s\n' "$TRADING_LIVE_MAX_NOTIONAL_CAP"
    printf '%s\n' ''
    printf '%s\n' '# Auth (portfolio-api)'
    printf 'AUTH_USERNAME=%s\n' "$AUTH_USERNAME"
    printf 'AUTH_PASSWORD=%s\n' "$AUTH_PASSWORD"
    printf 'AUTH_SECRET=%s\n' "$AUTH_SECRET"
    printf '%s\n' ''
    printf '%s\n' '# Internal API (ingest/signals → portfolio-api)'
    printf 'INTERNAL_API_KEY=%s\n' "$INTERNAL_API_KEY"
    printf 'MCP_SCHEMA_VERSION=v1\n'
    printf '%s\n' ''
    printf '%s\n' '# Ingest'
    printf 'INGEST_INTERVAL=10m\n'
    printf 'PORTFOLIO_API_URL=http://portfolio-api:8080\n'
    printf '%s\n' ''
    printf '%s\n' '# Signals'
    printf 'SIGNAL_RULES_PATH=./config/signals.yaml\n'
    printf 'SIGNAL_MOVE_THRESHOLD_PCT=2.5\n'
    printf 'SIGNAL_COOLDOWN=1h\n'
    printf 'SIGNAL_INTERVAL=5m\n'
    printf 'SIGNAL_STATE_PATH=./data/signal-state.json\n'
    printf 'SIGNAL_RULE_DEDUP_PATH=./data/signal-rules-dedup.json\n'
    printf 'SIGNAL_RULE_COOLDOWN=24h\n'
    printf 'SIGNAL_AGENT_MAX_PER_SYMBOL_24H=2\n'
    printf '%s\n' ''
    printf '%s\n' '# The Agent'
    printf 'AGENT_ENABLED=%s\n' "$AGENT_ENABLED"
    printf 'AGENT_PROVIDER=%s\n' "$AGENT_PROVIDER"
    printf 'AGENT_MODEL=%s\n' "${AGENT_MODEL:-claude-haiku-4-5}"
    printf 'ANTHROPIC_API_KEY=%s\n' "${ANTHROPIC_API_KEY:-}"
    printf 'AGENT_DAILY_COST_CAP_USD=%s\n' "${AGENT_DAILY_COST_CAP_USD:-5}"
    printf 'AGENT_DAILY_TIMER_UTC=%s\n' "${AGENT_DAILY_TIMER_UTC:-12:00}"
    printf 'AGENT_CONCURRENCY=%s\n' "${AGENT_CONCURRENCY:-2}"
    printf 'AGENT_PROMPT_PATH=config/agent-prompt.md\n'
    printf 'AGENT_TRADE_ENABLED=%s\n' "$AGENT_TRADE_ENABLED"
    printf 'AGENT_MIN_TRADE_CONFIDENCE=%s\n' "${AGENT_MIN_TRADE_CONFIDENCE:-0.70}"
    printf 'AGENT_DEFAULT_TRADE_NOTIONAL=%s\n' "${AGENT_DEFAULT_TRADE_NOTIONAL:-0}"
    printf '%s\n' ''
    if [[ -n "${DISCORD_WEBHOOK_URL:-}" ]]; then
      printf '%s\n' '# Discord (portfolio-api trade outcome webhooks)'
      printf 'DISCORD_WEBHOOK_URL=%s\n' "$DISCORD_WEBHOOK_URL"
      printf '%s\n' ''
    fi
    printf '%s\n' '# portfolio-api CORS (only if you set NEXT_PUBLIC_API_URL for direct browser → :8080)'
    printf 'CORS_ALLOWED_ORIGINS=%s\n' "$CORS_ALLOWED_ORIGINS"
    printf '%s\n' ''
    printf '%s\n' '# Web (Next.js rewrites /api-go to portfolio-api)'
    printf 'PORTFOLIO_API_INTERNAL_URL=http://portfolio-api:8080\n'
  } >> .env
}

compose_cmd() {
  case "$RUN_MODE" in
    dry) printf '%s' "docker compose" ;;
    paper|live) printf '%s' "docker compose -f docker-compose.yml -f docker-compose.coinbase.yml" ;;
    *) die "unknown RUN_MODE: $RUN_MODE" ;;
  esac
}

echo ""
echo "=== morgans-d-stonks quickstart ==="
echo ""

[[ -f .env.example ]] || die ".env.example is missing from the repo root."

CONFIGURE=true
if [[ -f .env ]]; then
  read -r -p ".env already exists. Reconfigure it with new prompts? [y/N] " overwrite || true
  case "${overwrite:-}" in
    y|Y|yes|YES) CONFIGURE=true ;;
    *) CONFIGURE=false ;;
  esac
fi

if [[ "$CONFIGURE" == true ]]; then
  echo ""
  echo "Enter values (press Enter to accept the default in brackets)."
  echo "Generated secrets avoid # in passwords so the .env file parses correctly."
  echo ""

  default_pg_pass="$(rand_hex)"
  POSTGRES_USER="$(read_default "Postgres username" "portfolio")"
  POSTGRES_PASSWORD="$(read_default "Postgres password" "$default_pg_pass")"
  POSTGRES_DB="$(read_default "Postgres database name" "portfolio")"

  AUTH_USERNAME="$(read_default "Dashboard login username" "admin")"
  default_auth_pass="$(rand_hex)"
  AUTH_PASSWORD="$(read_default "Dashboard login password" "$default_auth_pass")"
  echo -n "API session secret (min ~32 chars; press Enter to generate random): "
  read -r auth_secret_in || true
  if [[ -z "${auth_secret_in:-}" ]]; then
    AUTH_SECRET="$(rand_secret)"
    echo "(generated)"
  else
    AUTH_SECRET="$auth_secret_in"
  fi

  echo -n "Internal API key for ingest/signals (press Enter to generate random): "
  read -r internal_in || true
  if [[ -z "${internal_in:-}" ]]; then
    INTERNAL_API_KEY="$(rand_hex)$(rand_hex)"
    echo "(generated)"
  else
    INTERNAL_API_KEY="$internal_in"
  fi

  echo ""
  echo "Coinbase read API (CDP key with view/balance permissions):"
  COINBASE_READ_API_KEY="$(read_optional_empty "  COINBASE_READ_API_KEY")"
  COINBASE_READ_API_SECRET="$(read_secret_optional "  COINBASE_READ_API_SECRET")"

  select_run_mode

  if [[ "$RUN_MODE" == "live" ]]; then
    confirm_live_mode
  fi

  DISCORD_WEBHOOK_URL=""
  ANTHROPIC_API_KEY=""
  COINBASE_TRADE_API_KEY=""
  COINBASE_TRADE_API_SECRET=""
  TRADING_MAX_NOTIONAL="1000"
  TRADING_ALLOWED_SYMBOLS="BTC-USD,ETH-USD"
  TRADING_KILL_SWITCH="false"

  if [[ "$RUN_MODE" != "dry" ]]; then
    echo ""
    echo "Agent + trading policy (${RUN_MODE} mode):"
    ANTHROPIC_API_KEY="$(read_secret_optional "  ANTHROPIC_API_KEY")"
    TRADING_MAX_NOTIONAL="$(read_default "  TRADING_MAX_NOTIONAL (USD per order)" "1000")"
    TRADING_ALLOWED_SYMBOLS="$(read_default "  TRADING_ALLOWED_SYMBOLS" "BTC-USD,ETH-USD")"
    TRADING_KILL_SWITCH="$(read_default "  TRADING_KILL_SWITCH (true blocks all orders)" "false")"
    DISCORD_WEBHOOK_URL="$(read_optional_empty "  DISCORD_WEBHOOK_URL (trade outcome webhooks)")"

    if [[ "$RUN_MODE" == "live" ]]; then
      echo ""
      echo "Coinbase trade API (CDP key with trade permissions — separate from read key):"
      COINBASE_TRADE_API_KEY="$(read_optional_empty "  COINBASE_TRADE_API_KEY")"
      COINBASE_TRADE_API_SECRET="$(read_secret_optional "  COINBASE_TRADE_API_SECRET")"
      if [[ -z "${COINBASE_TRADE_API_KEY:-}" || -z "${COINBASE_TRADE_API_SECRET:-}" ]]; then
        die "Live mode requires COINBASE_TRADE_API_KEY and COINBASE_TRADE_API_SECRET."
      fi
    else
      echo ""
      echo "Paper mode: trade keys optional (simulated fills; leave empty unless testing key wiring)."
      COINBASE_TRADE_API_KEY="$(read_optional_empty "  COINBASE_TRADE_API_KEY")"
      COINBASE_TRADE_API_SECRET="$(read_secret_optional "  COINBASE_TRADE_API_SECRET")"
    fi
  else
    DISCORD_WEBHOOK_URL="$(read_optional_empty "Discord webhook URL (optional)")"
  fi

  CORS_ALLOWED_ORIGINS="http://localhost:3000,http://127.0.0.1:3000"

  write_env_file
  echo ""
  echo "Wrote .env for ${RUN_MODE} mode (keep it secret; do not commit)."
else
  echo "Using existing .env."
  if grep -q '^TRADING_BROKER_ENV=live' .env 2>/dev/null; then
    RUN_MODE="live"
  elif grep -q '^TRADING_ENABLED=true' .env 2>/dev/null; then
    RUN_MODE="paper"
  else
    RUN_MODE="dry"
  fi
  echo "Detected run mode from .env: ${RUN_MODE}"
fi

COMPOSE="$(compose_cmd)"

echo ""
echo "Compose command: ${COMPOSE}"
echo "  dry   → web, portfolio-api, ingest, signals, db"
echo "  paper → above + trading-worker (simulated fills)"
echo "  live  → above with BROKER_ENV=live (real Coinbase execution)"
echo ""
read -r -p "Build and start stack in ${RUN_MODE} mode? [Y/n] " start_confirm || true
case "${start_confirm:-Y}" in
  n|N|no|NO) echo "Skipped docker compose. Run manually when ready:"; echo "  ${COMPOSE} up -d --build"; exit 0 ;;
esac

echo ""
echo "Running: ${COMPOSE} build"
# shellcheck disable=SC2086
${COMPOSE} build

echo ""
echo "Running: ${COMPOSE} up -d"
# shellcheck disable=SC2086
${COMPOSE} up -d

echo ""
echo "Stack is running (${RUN_MODE} mode)."
echo "  Web:  http://localhost:3000"
echo "  API:  http://localhost:8080/api/health"
echo ""
if [[ "$RUN_MODE" == "live" ]]; then
  echo "  Live execution enabled — verify TRADING_MAX_NOTIONAL and kill switch before leaving unattended."
  echo ""
fi
echo "Logs:    ${COMPOSE} logs -f"
echo "Stop:    ${COMPOSE} down"
echo ""
